using System.Text;
using System.Text.Json;
using AgentNotify.Core.Delivery.Channels;

namespace AgentNotify.Tests;

/// <summary>
/// Cross-language agreement for envelope v1.
/// </summary>
/// <remarks>
/// The relay adapter shipped a placeholder that concatenated a random nonce, a random
/// public key and the plaintext, while the product documentation described a relay that
/// could not read notifications. These tests exist so that claim is checked rather than
/// asserted: the vectors in <c>TestData/relay-envelope-vectors.json</c> are generated by
/// the relay's TypeScript implementation, and the .NET output must match them byte for
/// byte. The Dart client will be held to the same file.
/// </remarks>
public sealed class RelayEnvelopeCryptoTests
{
    private sealed record Vector(
        string Name,
        string Version,
        string SenderId,
        string RecipientId,
        string KeyId,
        string EventId,
        string ExpiresAt,
        string Plaintext,
        string RecipientPublicKey,
        string EphemeralPrivateKey,
        string Nonce,
        string Ciphertext,
        string Aad);

    private static IEnumerable<Vector> LoadVectors()
    {
        var path = Path.Combine(AppContext.BaseDirectory, "TestData", "relay-envelope-vectors.json");
        using var document = JsonDocument.Parse(File.ReadAllText(path));
        foreach (var element in document.RootElement.GetProperty("vectors").EnumerateArray())
        {
            // The file also carries opaque-validation vectors, which have no plaintext.
            if (!element.TryGetProperty("plaintext", out _)) continue;
            yield return new Vector(
                element.GetProperty("name").GetString()!,
                element.GetProperty("version").GetString()!,
                element.GetProperty("senderId").GetString()!,
                element.GetProperty("recipientId").GetString()!,
                element.GetProperty("keyId").GetString()!,
                element.GetProperty("eventId").GetString()!,
                element.GetProperty("expiresAt").GetString()!,
                element.GetProperty("plaintext").GetString()!,
                element.GetProperty("recipientPublicKey").GetString()!,
                element.GetProperty("ephemeralPrivateKey").GetString()!,
                element.GetProperty("nonce").GetString()!,
                element.GetProperty("ciphertext").GetString()!,
                element.GetProperty("aad").GetString()!);
        }
    }

    public static TheoryData<string> VectorNames()
    {
        var data = new TheoryData<string>();
        foreach (var vector in LoadVectors()) data.Add(vector.Name);
        return data;
    }

    [Theory]
    [MemberData(nameof(VectorNames))]
    public void ReproducesRelayVectorByteForByte(string name)
    {
        var vector = LoadVectors().Single(v => v.Name == name);

        var sealedEnvelope = RelayEnvelopeCrypto.Seal(
            Encoding.UTF8.GetBytes(vector.Plaintext),
            RelayEnvelopeCrypto.DecodeBase64Url(vector.RecipientPublicKey),
            RelayEnvelopeCrypto.DecodeBase64Url(vector.EphemeralPrivateKey),
            RelayEnvelopeCrypto.DecodeBase64Url(vector.Nonce),
            RelayEnvelopeCrypto.BuildAssociatedData(
                vector.Version,
                vector.SenderId,
                vector.RecipientId,
                vector.KeyId,
                vector.EventId,
                vector.ExpiresAt));

        Assert.Equal(vector.Ciphertext, sealedEnvelope);
    }

    [Theory]
    [MemberData(nameof(VectorNames))]
    public void BuildsTheSameAssociatedDataAsTheRelay(string name)
    {
        var vector = LoadVectors().Single(v => v.Name == name);
        var aad = RelayEnvelopeCrypto.BuildAssociatedData(
            vector.Version,
            vector.SenderId,
            vector.RecipientId,
            vector.KeyId,
            vector.EventId,
            vector.ExpiresAt);

        // A mismatch here decrypts to nothing on the phone with no useful error,
        // so it is worth asserting separately from the ciphertext.
        Assert.Equal(vector.Aad, Encoding.UTF8.GetString(aad));
    }

    [Fact]
    public void SealedEnvelopeCarriesNoPlaintext()
    {
        var vector = LoadVectors().First();
        var sealedEnvelope = RelayEnvelopeCrypto.Seal(
            "{\"title\":\"Deploy finished\",\"message\":\"staging is green\"}",
            vector.RecipientPublicKey,
            vector.SenderId,
            vector.RecipientId,
            vector.KeyId,
            vector.EventId,
            vector.ExpiresAt);

        // The placeholder this replaced would have failed every one of these.
        var wire = RelayEnvelopeCrypto.DecodeBase64Url(sealedEnvelope);
        var asText = Encoding.UTF8.GetString(wire);
        Assert.DoesNotContain("Deploy finished", asText, StringComparison.Ordinal);
        Assert.DoesNotContain("staging is green", asText, StringComparison.Ordinal);
        Assert.DoesNotContain("title", asText, StringComparison.Ordinal);
    }

    [Fact]
    public void UsesAFreshNonceAndEphemeralKeyForEveryEnvelope()
    {
        var vector = LoadVectors().First();

        string Seal() => RelayEnvelopeCrypto.Seal(
            "same plaintext every time",
            vector.RecipientPublicKey,
            vector.SenderId,
            vector.RecipientId,
            vector.KeyId,
            vector.EventId,
            vector.ExpiresAt);

        var envelopes = Enumerable.Range(0, 8).Select(_ => Seal()).ToArray();

        // Identical input must not produce identical output: a repeated nonce under the
        // same key would leak the relationship between two notifications.
        Assert.Equal(envelopes.Length, envelopes.Distinct(StringComparer.Ordinal).Count());

        foreach (var envelope in envelopes)
        {
            var wire = RelayEnvelopeCrypto.DecodeBase64Url(envelope);
            Assert.True(wire.Length >= RelayEnvelopeCrypto.MinimumWireLength);
        }

        var nonces = envelopes
            .Select(e => Convert.ToHexString(RelayEnvelopeCrypto.DecodeBase64Url(e).AsSpan(0, 24).ToArray()))
            .ToArray();
        Assert.Equal(nonces.Length, nonces.Distinct(StringComparer.Ordinal).Count());
    }

    [Fact]
    public void RejectsAKeyThatIsNotAUsablePublicKey()
    {
        var vector = LoadVectors().First();

        string SealWith(string key) => RelayEnvelopeCrypto.Seal(
            "payload",
            key,
            vector.SenderId,
            vector.RecipientId,
            vector.KeyId,
            vector.EventId,
            vector.ExpiresAt);

        // Wrong length.
        Assert.Throws<ArgumentException>(() => SealWith("c2hvcnQ"));

        // All zeros is a small-order point: the agreement produces an all-zero shared
        // secret, which would encrypt under a key an attacker also knows.
        var zeros = RelayEnvelopeCrypto.EncodeBase64Url(new byte[32]);
        Assert.Throws<ArgumentException>(() => SealWith(zeros));

        // Not base64url at all.
        Assert.ThrowsAny<Exception>(() => SealWith("!!!not-base64!!!"));
    }

    [Fact]
    public void AssociatedDataBindsEveryRoutingField()
    {
        var vector = LoadVectors().First();
        var baseline = RelayEnvelopeCrypto.BuildAssociatedData(
            vector.Version, vector.SenderId, vector.RecipientId,
            vector.KeyId, vector.EventId, vector.ExpiresAt);

        // Changing any one field must change the AAD, or an envelope could be replayed
        // against a different device, key, or expiry without failing authentication.
        var variants = new[]
        {
            RelayEnvelopeCrypto.BuildAssociatedData("2", vector.SenderId, vector.RecipientId, vector.KeyId, vector.EventId, vector.ExpiresAt),
            RelayEnvelopeCrypto.BuildAssociatedData(vector.Version, "other-sender", vector.RecipientId, vector.KeyId, vector.EventId, vector.ExpiresAt),
            RelayEnvelopeCrypto.BuildAssociatedData(vector.Version, vector.SenderId, "other-device", vector.KeyId, vector.EventId, vector.ExpiresAt),
            RelayEnvelopeCrypto.BuildAssociatedData(vector.Version, vector.SenderId, vector.RecipientId, "other-key", vector.EventId, vector.ExpiresAt),
            RelayEnvelopeCrypto.BuildAssociatedData(vector.Version, vector.SenderId, vector.RecipientId, vector.KeyId, "other-event", vector.ExpiresAt),
            RelayEnvelopeCrypto.BuildAssociatedData(vector.Version, vector.SenderId, vector.RecipientId, vector.KeyId, vector.EventId, "2030-01-01T00:00:00Z"),
        };

        foreach (var variant in variants)
            Assert.NotEqual(Convert.ToHexString(baseline), Convert.ToHexString(variant));
    }
}
